[package]
name = "k_nearust_neighbors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustlearn = "^0.4.3"
rand = "0.8.4"